### ISSUE TITLE
0.015?

### ISSUE THREAD

**Issue by kloczek** [exodist/Term-Table#10]
https://metacpan.org/release/Term-Table/ says that latest version iis 0.015.
Which site is correct? or this is no longer git repo of that module?

**Comment by exodist** [comment]
I am not 100% sure what your question is about?

Version 0.015 is the latest version, as metacpan says

Is your confusion because the github repo has version 0.016 in the module? Dist::Zilla automatically bumps the repo version upon release, meaning the moment 0.016 is released the repo will say version 0.017.

**Comment by exodist** [comment]
Note that there is no version 0.016 in the tags.... and as I check there I see there is also no 0.015, which I am guessing is the cause of this ticket?  Though if that is the case this ticket was extremely unclear. I will see if I have the tag locally, if so I will push it.

**Comment by exodist** [comment]
I had the tag locally, and I pushed it. The tag should now show up on the tags list on github.

For future reference a helpful issue title/description would have been: Metacpan has version 0.015, but there is no 0.015 tag on github.
